site_name: Nominatim Documentation
theme: readthedocs
docs_dir: ${CMAKE_CURRENT_BINARY_DIR}
site_url: https://nominatim.org
repo_url: https://github.com/openstreetmap/Nominatim
pages:
    - 'Introduction' : 'index.md'
    - 'API Reference':
        - 'Overview': 'api/Overview.md'
        - 'Search': 'api/Search.md'
        - 'Reverse': 'api/Reverse.md'
        - 'Address Lookup': 'api/Lookup.md'
        - 'Details' : 'api/Details.md'
        - 'Status' : 'api/Status.md'
        - 'Place Output Formats': 'api/Output.md'
        - 'FAQ': 'api/Faq.md'
    - 'Administration Guide':
        - 'Basic Installation': 'admin/Installation.md'
        - 'Import' : 'admin/Import.md'
        - 'Update' : 'admin/Update.md'
        - 'Deploy' : 'admin/Deployment.md'
        - 'Nominatim UI'  : 'admin/Setup-Nominatim-UI.md'
        - 'Advanced Installations' : 'admin/Advanced-Installations.md'
        - 'Maintenance' : 'admin/Maintenance.md'
        - 'Migration from older Versions' : 'admin/Migration.md'
        - 'Troubleshooting' : 'admin/Faq.md'
    - 'Customization Guide':
        - 'Overview': 'customize/Overview.md'
        - 'Import Styles': 'customize/Import-Styles.md'
        - 'Configuration Settings': 'customize/Settings.md'
        - 'Place Ranking' : 'customize/Ranking.md'
        - 'Tokenizers' : 'customize/Tokenizers.md'
        - 'Special Phrases': 'customize/Special-Phrases.md'
        - 'External data: US housenumbers from TIGER': 'customize/Tiger.md'
        - 'External data: Postcodes': 'customize/Postcodes.md'
    - 'Developers Guide':
        - 'Architecture Overview' : 'develop/overview.md'
        - 'Database Layout' : 'develop/Database-Layout.md'
        - 'Tokenizers' : 'develop/Tokenizers.md'
        - 'Setup for Development' : 'develop/Development-Environment.md'
        - 'Testing' : 'develop/Testing.md'
        - 'External Data Sources': 'develop/data-sources.md'
    - 'Appendix':
        - 'Installation on CentOS 7' : 'appendix/Install-on-Centos-7.md'
        - 'Installation on CentOS 8' : 'appendix/Install-on-Centos-8.md'
        - 'Installation on Ubuntu 18' : 'appendix/Install-on-Ubuntu-18.md'
        - 'Installation on Ubuntu 20' : 'appendix/Install-on-Ubuntu-20.md'
markdown_extensions:
    - codehilite
    - admonition
    - def_list
    - toc:
        permalink: ÔÉÅ
extra_css: [extra.css, styles.css]
plugins:
    - search
    - mkdocstrings:
        handlers:
          python:
            rendering:
              show_source: false
              show_signature_annotations: false
