name: Windows CI (experimental)

on:
  pull_request:
  push:

jobs:
  windows-smoke:
    runs-on: windows-latest
    continue-on-error: true #this is a smoke test (experimental); it won't block merges

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip
          cache-dependency-path: |
            packaging/nominatim-db/pyproject.toml
            packaging/nominatim-api/pyproject.toml

      - name: Set up virtual environment
        run: |
          python -m venv venv
          venv\\Scripts\\python -m pip install -U pip

      - name: Install dependencies
        run: venv\\Scripts\\pip install packaging\\nominatim-db packaging\\nominatim-api

      - name: Install latest flake8
        run: venv\\Scripts\\pip install -U flake8

      - name: Python linting
        run: venv\\Scripts\\python -m flake8 src test/python test/bdd

      - name: Run CLI smoke test
        run: venv\\Scripts\\nominatim --help
